--- crates/arti/Cargo.toml.orig	2026-01-13 15:58:28 UTC
+++ crates/arti/Cargo.toml
@@ -20,7 +20,6 @@ default = [
 default = [
     "default-runtime",
     "dns-proxy",
-    "harden",
     "compression",
     "bridge-client",
     "pt-client",
@@ -40,7 +39,6 @@ full = [
     "journald",
     "arti-client/full",
     "dns-proxy",
-    "harden",
     "compression",
     "bridge-client",
     "pt-client",
