--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -37,7 +37,7 @@ dependencies = [
 ]
 dependencies = [
   "awkward >=2.5.1",
-  "dask >=2023.04.0,<2025.4.0",
+  "dask >=2023.04.0",
   "cachetools",
   "typing_extensions >=4.8.0",
 ]
