--- pyproject.toml.orig	2025-11-29 02:08:01 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [project]
-name = "Werkzeug"
+name = "werkzeug"
 version = "3.1.4"
 description = "The comprehensive WSGI web application library."
 readme = "README.md"
