--- pyproject.toml.orig	2025-11-06 10:53:27 UTC
+++ pyproject.toml
@@ -1,12 +1,10 @@
 [project]
-name = "vfbLib"
+name = "vfblib"
 dynamic = ["version"]
 description = "Tools for converting FontLab Studio 5 (VFB) files."
 keywords = ["vfb", "vfbLib", "fonttools"]
 
 readme = "README.md"
-license = "GPL-3.0-or-later"
-license-files = ["LICENSE"]
 
 authors = [{ name = "Jens KutÃ­lek", email = "webmail@kutilek.de" }]
 classifiers = [
@@ -73,7 +71,7 @@ vfbdiff = "vfbLib.diff:diffvfb"
 # yuri = vfbLib.value:yuri
 
 [build-system]
-requires = ["setuptools>=80.9.0", "setuptools-scm[toml]>=9.2.0", "wheel"]
+requires = ["setuptools>=61", "setuptools-scm[toml]>=6.2", "wheel"]
 build-backend = "setuptools.build_meta"
 
 [tool.setuptools.package-data]
