--- ruff/crates/ty/Cargo.toml.orig	2006-07-24 01:21:28 UTC
+++ ruff/crates/ty/Cargo.toml
@@ -40,7 +40,7 @@ wild = { workspace = true }
 tracing-subscriber = { workspace = true }
 wild = { workspace = true }
 
-[target.'cfg(all(not(target_os = "macos"), not(target_os = "windows"), not(target_os = "openbsd"), not(target_os = "aix"), not(target_os = "android"), any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "powerpc64", target_arch = "riscv64")))'.dependencies]
+[target.'cfg(all(not(target_os = "macos"), not(target_os = "windows"), not(target_os = "openbsd"), not(target_os = "freebsd"), not(target_os = "aix"), not(target_os = "android"), any(target_arch = "x86_64", target_arch = "aarch64", target_arch = "powerpc64", target_arch = "riscv64")))'.dependencies]
 tikv-jemallocator = { workspace = true }
 
 [dev-dependencies]
