--- pyproject.toml.orig	2025-12-24 19:21:09 UTC
+++ pyproject.toml
@@ -1,9 +1,7 @@ requires = [
 [build-system]
 requires = [
-	"setuptools>=77",
+	"setuptools>=61",
 	"setuptools_scm[toml]>=3.4.1",
-	# jaraco/skeleton#174
-	"coherent.licensed",
 ]
 build-backend = "setuptools.build_meta"
 
@@ -21,7 +19,7 @@ requires-python = ">=3.9"
 	"Programming Language :: Python :: 3 :: Only",
 ]
 requires-python = ">=3.9"
-license = "MIT"
+license = { text = "MIT" }
 dependencies = [
 	'backports.tarfile; python_version < "3.12"',
 ]
