--- lapce-proxy/Cargo.toml.orig	2022-08-23 19:54:34 UTC
+++ lapce-proxy/Cargo.toml
@@ -37,7 +37,7 @@ toml_edit = { version = "0.14.4", features = ["easy"] 
 serde_json = "1.0.59"
 anyhow = "1.0.32"
 toml_edit = { version = "0.14.4", features = ["easy"] }
-git2 = { version = "0.14.4", features = ["vendored-openssl"] }
+git2 = { version = "0.14.4", features = [] }
 lapce-core = { path = "../lapce-core" }
 lapce-rpc = { path = "../lapce-rpc" }
 trash = "2.1"
