--- pyproject.toml.orig	2022-11-09 12:37:21 UTC
+++ pyproject.toml	2026-01-27 15:33:20.626221000 -0800
@@ -64,14 +64,12 @@
 backend-path = ["./"]
 requires = [
     "scikit-build-core>=0.11.4",
-	"pybind11[global]>=2.6.0",
+	"pybind11>=2.6.0",
     "setuptools_scm>=8.0",
 ]
 
 [tool.scikit-build]
 minimum-version = "0.10"
-cmake.version = ">=3.29.0"
-ninja.version = ">=1.10"
 ninja.make-fallback = false
 metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
 
@@ -283,9 +281,7 @@
     "requests>=2.32.4",
 ]
 build = [
-    "cmake>=3.29.0",
-    "ninja>=1.10",
-    "pybind11[global]>=2.6.0",
+    "pybind11>=2.6.0",
     "scikit_build_core>=0.11.4",
     "setuptools_scm>=8.0",
 ]
