--- pyproject.toml.orig	2025-11-13 17:58:14 UTC
+++ pyproject.toml
@@ -34,10 +34,10 @@ requires = [
 [build-system]
 requires = [
     "build>=1.1",
-    "pip>=24.0",
+    "pip>=23.3.2",
     "pipx>=1.5",
     "packaging>=20.0",
-    "setuptools>=78.1.0",
+    "setuptools>=63.1.0",
     "wheel>=0.42.0",
 ]
 build-backend = "setuptools.build_meta"
