--- pyproject.toml.orig	2025-11-03 12:04:09 UTC
+++ pyproject.toml
@@ -34,8 +34,8 @@ requires = [
 [build-system]
 requires = [
     "build>=1.1",
-    "pip>=24.0",
-    "setuptools>=78.1.0",
+    "pip>=23.3.2",
+    "setuptools>=63.1.0",
     "wheel>=0.42.0",
 ]
 build-backend = "setuptools.build_meta"
