--- pyproject.toml.orig	2025-11-27 06:34:00 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@
 [build-system]
 # require a recent setuptools for `license = ` support
-requires = ["setuptools >= 78.1.0", "wheel"]
+requires = ["setuptools >= 61.0", "wheel"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -60,7 +60,7 @@ There are also [optional extras available](https://hyp
 
 There are also [optional extras available](https://hypothesis.readthedocs.io/en/latest/extras.html).
 """, "content-type" = "text/markdown"}
-license = "MPL-2.0"
+license = { text = "MPL-2.0" }
 requires-python = ">= 3.10"
 keywords = ["python", "testing", "fuzzing", "property-based-testing"]
 classifiers = [
