--- Cargo.toml.orig	2026-01-12 05:28:04 UTC
+++ Cargo.toml
@@ -1,6 +1,6 @@ name = "hbbs"
 [package]
 name = "hbbs"
-version = "1.1.14"
+version = "1.1.15"
 authors = ["rustdesk <info@rustdesk.com>"]
 edition = "2021"
 build = "build.rs"
