--- pyproject.toml.orig	2025-11-06 16:54:27 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=80", "setuptools-scm"]
+requires = ["setuptools>=62.2", "setuptools-scm"]
 build-backend = "setuptools.build_meta"
 
 [project]
