--- pyproject.toml.orig	2025-12-04 14:39:27 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@ requires = [
 [build-system]
 build-backend = "setuptools.build_meta"
 requires = [
-  "setuptools>=78.0.2"
+  "setuptools>=61"
 ]
 
 [dependency-groups]
@@ -76,8 +76,7 @@ keywords = [
 keywords = [
   "i18n l10n gettext translate"
 ]
-license = "GPL-2.0-or-later"
-license-files = ["COPYING"]
+license = { text = "GPL-2.0-or-later" }
 name = "translate-toolkit"
 requires-python = ">=3.10"
 
@@ -92,10 +91,10 @@ ical = [
   "fluent.syntax>=0.19.0,<0.20"
 ]
 ical = [
-  "vobject==0.9.9"
+  "vobject>=0.9.6.1"
 ]
 ini = [
-  "iniparse==0.5"
+  "iniparse>=0.5"
 ]
 levenshtein = [
   "python-Levenshtein>=0.21.0"
@@ -110,13 +109,13 @@ spellcheck = [
   "pyparsing>=3.2.0,<3.3"
 ]
 spellcheck = [
-  "pyenchant==3.3.0"
+  "pyenchant>=3.3.0"
 ]
 subtitles = [
   "aeidon>=1.14.1,<1.16"
 ]
 tmserver = [
-  "cheroot==11.1.2"
+  "cheroot>=11.1.2"
 ]
 toml = [
   "tomlkit>=0.13.0,<0.14.0"
