--- rollup/rust/bindings_napi/Cargo.toml.orig	2026-02-16 10:45:29 UTC
+++ rollup/rust/bindings_napi/Cargo.toml
@@ -15,10 +15,10 @@ napi-derive = "2.16.12"
 parse_ast = { path = "../parse_ast" }
 xxhash = { path = "../xxhash" }
 
-[target.'cfg(not(target_os = "linux"))'.dependencies]
+[target.'cfg(not(any(target_os = "linux", target_os = "freebsd", target_os = "openbsd")))'.dependencies]
 mimalloc-rust = { version = "0.2.1" }
 
-[target.'cfg(all(target_os = "linux", not(all(target_env = "musl", target_arch = "aarch64"))))'.dependencies]
+[target.'cfg(any(all(target_os = "linux", not(all(target_env = "musl", target_arch = "aarch64"))), all(target_os = "freebsd", not(target_arch = "aarch64")), all(target_os = "openbsd", not(target_arch = "aarch64"))))'.dependencies]
 mimalloc-rust = { version = "0.2.1", features = ["local-dynamic-tls"] }
 
 [build-dependencies]
