--- pyproject.toml.orig	2026-01-29 11:20:02.000000000 -0800
+++ pyproject.toml	2026-01-30 06:06:24.331402000 -0800
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 66.1.0, <= 80.10.2", "wheel == 0.45.1"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
+requires = ["setuptools >= 63.1.0, <= 80.10.2", "wheel >= 0.45.1"]  # lower bound to support controller Python versions, upper bound for latest version tested at release
 build-backend = "setuptools.build_meta"
 
 [project]
