--- pyproject.toml.orig	2026-02-16 06:35:56 UTC
+++ pyproject.toml
@@ -19,7 +19,6 @@ dependencies = [
     "scipy != 1.11.0, != 1.11.1, != 1.11.2, !=1.17.0",
     "spglib>=2.5",
 ]
-license-files = ["LICENSE"]
 
 [project.urls]
 "Homepage" = "https://github.com/symfc/symfc"
