--- pyproject.toml.orig	2025-10-26 09:59:30 UTC
+++ pyproject.toml
@@ -9,7 +9,7 @@ requires-python = ">=3.9"
 description = "HTTP client library for gevent"
 readme = "README.md"
 requires-python = ">=3.9"
-license = "MIT"
+license = {file = "LICENSE-MIT"}
 keywords = ["http", "gevent", "client"]
 authors = [{name = "Antonin Amand", email = "antonin.amand@gmail.com"}]
 classifiers = [
