--- pyproject.toml.orig	2025-12-29 20:33:13 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@ build-backend = "setuptools.build_meta"
 [build-system]
 # Requirements for building the compiled package
 build-backend = "setuptools.build_meta"
-requires = ["wheel", "setuptools >=40.8", "setuptools_scm[toml]>=6.2", "cython >=3", "numpy >=2.0"]
+requires = ["wheel", "setuptools >=40.8", "setuptools_scm[toml]>=6.2", "cython >=3", "numpy"]
 
 [tool.setuptools_scm]
 
@@ -22,7 +22,7 @@ classifiers = [
     "Programming Language :: Python :: 3",
     "License :: OSI Approved :: GNU Affero General Public License v3"
 ]
-license-files = ["LICENSE"]
+license = {file = "LICENSE"}
 requires-python = ">=3.10"
 
 [project.urls]
@@ -71,4 +71,4 @@ exclude_lines = [
     "raise NotImplementedError",
     "except ModuleNotFoundError:",
     "except ImportError",
-]
\ No newline at end of file
+]
