--- pyproject.toml.orig	2025-08-03 20:19:11 UTC
+++ pyproject.toml
@@ -16,9 +16,7 @@ requires = [
     # Note that building against numpy 1.x works fine too - users and
     # redistributors can do this by installing the numpy version they like and
     # disabling build isolation.
-    "numpy>=2.0.0; python_version<'3.13'",
-    "numpy>=2.1.0; python_version>='3.13'",
-    "numpy>=2.3.2; python_version>='3.14'",
+    "numpy",
 ]
 
 [project]
