--- pyproject.toml.orig	2026-01-03 16:40:12 UTC
+++ pyproject.toml
@@ -5,7 +5,7 @@ requires = [
     # Next step should be >= 77.0 for PEP 639 support
     # Don't bump too early to give distributors time to update
     # their setuptools version.
-    "setuptools >= 67.0",
+    "setuptools >= 61.0",
 ]
 build-backend = "setuptools.build_meta"
 
@@ -49,7 +49,7 @@ speedups = [
 
 [project.optional-dependencies]
 speedups = [
-  "aiodns >= 3.3.0",
+  "aiodns >= 3.2.0",
   "Brotli >= 1.2; platform_python_implementation == 'CPython'",
   "brotlicffi >= 1.2; platform_python_implementation != 'CPython'",
   "backports.zstd; platform_python_implementation == 'CPython' and python_version < '3.14'",
