--- pyproject.toml.orig	2025-11-17 14:11:29 UTC
+++ pyproject.toml
@@ -13,7 +13,6 @@ dependencies = [
 license = { file = "LICENSE" }
 requires-python = ">=3.9"
 dependencies = [
-    "hypothesis>=6.137.0",
     "crosshair-tool>=0.0.97"
 ]
 classifiers = [
