--- pyproject.toml.orig	1970-01-01 00:00:00 UTC
+++ pyproject.toml
@@ -10,7 +10,7 @@ python = "^3.8.0"
 
 [tool.poetry.dependencies]
 python = "^3.8.0"
-thrift = ">=0.16.0,<0.21.0"
+thrift = ">=0.16.0"
 pandas = [
     { version = ">=1.2.5,<2.4.0", python = ">=3.8,<3.13" },
     { version = ">=2.2.3,<2.4.0", python = ">=3.13" }
@@ -31,7 +31,7 @@ pybreaker = "^1.0.0"
 ]
 pyjwt = "^2.0.0"
 pybreaker = "^1.0.0"
-requests-kerberos = {version = "^0.15.0", optional = true}
+requests-kerberos = {version = "<0.16", optional = true}
 
 
 [tool.poetry.extras]
@@ -92,4 +92,4 @@ skip_covered = false
 skip_covered = false
 
 [tool.coverage.xml]
-output = "coverage.xml"
\ No newline at end of file
+output = "coverage.xml"
