Relax version requirements of py-setuptools and enable build for older versions
of it.

--- pyproject.toml.orig	2025-11-03 11:21:39 UTC
+++ pyproject.toml
@@ -4,7 +4,6 @@ requires-python = ">=3.7"
 description = "Sane and flexible OpenAPI 3 schema generation for Django REST framework"
 readme = "README.rst"
 requires-python = ">=3.7"
-license = "BSD-3-Clause"
 authors = [
     {name = "T. Franzel", email = "tfranzel@gmail.com"}
 ]
@@ -57,6 +56,9 @@ Documentation = "https://drf-spectacular.readthedocs.i
 Source = "https://github.com/tfranzel/drf-spectacular"
 Documentation = "https://drf-spectacular.readthedocs.io"
 
+[project.license]
+text = "BSD-3-Clause"
+
 [tool.setuptools.dynamic]
 version = {attr = "drf_spectacular.__version__"}
 
@@ -72,5 +74,5 @@ drf_spectacular = [
 ]
 
 [build-system]
-requires = ["setuptools>=75.3.2", "wheel"]
+requires = ["setuptools", "wheel"]
 build-backend = "setuptools.build_meta"
