--- pyproject.toml.orig	2025-11-12 12:17:14 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ requires = [
 [build-system]
 requires = [
-    "setuptools>=80",
+    "setuptools>=61",
 ]
 build-backend = "setuptools.build_meta"
 
@@ -10,8 +10,7 @@ version = "3.2.2"
 ]
 name = "tblib"
 version = "3.2.2"
-license = "BSD-2-Clause"
-license-files = ["LICENSE"]
+license = {text = "BSD-2-Clause"}
 description = "Traceback serialization library."
 authors = [
     { name = "Ionel Cristian Mărieș", email = "contact@ionelmc.ro" },
