--- pyproject.toml.orig	2025-11-14 07:27:59 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ requires = [
 [build-system]
 requires = [
-    "setuptools>=77.0.3",
+    "setuptools>=61",
     "wheel",
 ]
 build-backend = "setuptools.build_meta"
@@ -11,7 +11,7 @@ description = "Microsoft Azure Mysqlflexibleservers Ma
     { name = "Microsoft Corporation", email = "azpysdkhelp@microsoft.com" },
 ]
 description = "Microsoft Azure Mysqlflexibleservers Management Client Library for Python"
-license = "MIT"
+license = { text = "MIT" }
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Programming Language :: Python",
