--- pyproject.toml.orig	2025-12-11 12:56:23 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@
 # LocalStack project configuration
 [build-system]
-requires = ['setuptools>=64', 'wheel', 'plux>=1.12', "setuptools_scm>=8.1"]
+requires = ['setuptools>=61', 'wheel', 'plux>=1.12', "setuptools_scm>=8"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -9,14 +9,14 @@ description = "The core library and runtime of LocalSt
     { name = "LocalStack Contributors", email = "info@localstack.cloud" }
 ]
 description = "The core library and runtime of LocalStack"
-license = "Apache-2.0"
+license = { text = "Apache-2.0" }
 requires-python = ">=3.10"
 dependencies = [
     "asn1crypto>=1.5.1",
-    "click>=8.2.0",
+    "click>=8.1.0",
     "cachetools>=5.0",
     "cryptography",
-    "dill==0.3.6",
+    "dill>=0.3.6",
     "dnslib>=0.9.10",
     "dnspython>=1.16.0",
     "plux>=1.10",
@@ -52,9 +52,9 @@ base-runtime = [
 # minimal required to actually run localstack on the host for services natively implemented in python
 base-runtime = [
     # pinned / updated by ASF update action
-    "boto3==1.42.4",
+    "boto3>=1.42.4",
     # pinned / updated by ASF update action
-    "botocore==1.42.4",
+    "botocore>=1.42.4",
     # transitive dependency of botocore, added to avoid specific version
     "awscrt>=0.13.14,!=0.27.1",
     "cbor2>=5.5.0",
