--- pyproject.toml.orig	2026-01-29 07:53:27 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@
 # LocalStack project configuration
 [build-system]
-requires = ['setuptools>=64', 'wheel', 'plux>=1.12', "setuptools_scm>=8.1"]
+requires = ['setuptools>=61', 'wheel', 'plux>=1.12', "setuptools_scm>=8.1"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -9,11 +9,11 @@ description = "The core library and runtime of LocalSt
     { name = "LocalStack Contributors", email = "info@localstack.cloud" }
 ]
 description = "The core library and runtime of LocalStack"
-license = "Apache-2.0"
+license = { text = "Apache-2.0" }
 requires-python = ">=3.10"
 dependencies = [
     "asn1crypto>=1.5.1",
-    "click>=8.2.0",
+    "click>=8.1.0",
     "cachetools>=5.0",
     "cryptography",
     "dnslib>=0.9.10",
