--- pyproject.toml.orig	2023-12-07 13:22:55 UTC
+++ pyproject.toml
@@ -3,14 +3,11 @@
 # INSTALL_REQUIRES in setup.py
 requires = [
     "setuptools>=69.0.2; python_version>='3.12'",
-    "setuptools>=63.4.3",
+    "setuptools>=63.1.0",
     "cython>=0.29.33,<4",  # Sync with CYTHON_MIN_VER in setup
-    # Workaround for oldest supported numpy using 1.21.6, but SciPy 1.9.2+ requiring 1.22.3+
-    "oldest-supported-numpy; python_version!='3.10' or platform_system!='Windows' or platform_python_implementation=='PyPy'",
-    "numpy>=1.22.3,<2; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",
-    "numpy<2; python_version>='3.12'",
+    "numpy>=1.22.3,<2",
     "scipy>=1.4",
-    "setuptools_scm[toml]>=8,<9"
+    "setuptools_scm[toml]>=6,<9"
 ]
 build-backend = "setuptools.build_meta"
 
