remove after setuptools update past 70.1

--- pyproject.toml.orig	2026-02-08 15:20:31 UTC
+++ pyproject.toml
@@ -71,7 +71,7 @@ requires = [
 
 [build-system]
 requires = [
-    "setuptools>=70.1",
+    "setuptools",
     "cython >= 3.0.10",
     "requests >= 2.26.0",
     "sip == 6.12.0",
