--- Cargo.toml.orig	2025-06-26 08:44:25 UTC
+++ Cargo.toml
@@ -139,7 +139,6 @@ git = ["git2"]
 [features]
 default = ["git"]
 git = ["git2"]
-vendored-openssl = ["git2/vendored-openssl"]
 vendored-libgit2 = ["git2/vendored-libgit2"]
 # Should only be used inside of flake.nix
 nix = []
