--- rust/stracciatella/Cargo.toml.orig	2025-10-05 09:24:39 UTC
+++ rust/stracciatella/Cargo.toml
@@ -35,24 +35,6 @@ simplelog = "0.12"
 slug = "0.1.4"
 simplelog = "0.12"
 
-[target.'cfg(windows)'.dependencies.winapi]
-# @see stracciatella::fs::free_space
-version = "0.3"
-features = ["std", "fileapi"]
-
-[target.'cfg(target_os = "android")'.dependencies.send_wrapper]
-version = "0.6"
-[target.'cfg(target_os = "android")'.dependencies.lazy_static]
-version = "1.4"
-[target.'cfg(target_os = "android")'.dependencies.jni]
-version = "0.19"
-[target.'cfg(target_os = "android")'.dependencies.jni-sys]
-version = "0.3"
-[target.'cfg(target_os = "android")'.dependencies.ndk]
-version = "0.7"
-[target.'cfg(target_os = "android")'.dependencies.ndk-sys]
-version = "0.4"
-
 [build-dependencies]
 serde = "1.0"
 serde_json = "1.0"
