--- pyproject.toml.orig	2024-02-05 21:17:48 UTC
+++ pyproject.toml
@@ -1,8 +1,8 @@ requires = [
 [build-system]
 build-backend = "mesonpy"
 requires = [
-    "Cython>=0.29.34,<3.1",
-    "meson-python>=0.15.0,<0.16.0",
+    "Cython>=0.29.34",
+    "meson-python>=0.15.0",
 ]
 
 [project]
