--- pyproject.toml.orig	2023-11-15 07:57:02 UTC
+++ pyproject.toml
@@ -45,7 +45,7 @@ pathable = "^0.4.1"
 python = "^3.8.0"
 PyYAML = ">=5.1"
 requests = {version = "^2.31.0", optional = true}
-referencing = ">=0.28.0,<0.32.0"
+referencing = ">=0.28.0,<0.33.0"
 
 [tool.poetry.dev-dependencies]
 pre-commit = "*"
