--- pyproject.toml.orig	2026-01-10 09:08:31 UTC
+++ pyproject.toml
@@ -6,7 +6,7 @@ requires-python = ">=3.10"
 name = "websockets"
 description = "An implementation of the WebSocket Protocol (RFC 6455 & 7692)"
 requires-python = ">=3.10"
-license = "BSD-3-Clause"
+license = { text = "BSD-3-Clause" }
 authors = [
     { name = "Aymeric Augustin", email = "aymeric.augustin@m4x.org" },
 ]
