--- rollup/rust/bindings_napi/Cargo.toml.orig	2024-03-28 11:20:35 UTC
+++ rollup/rust/bindings_napi/Cargo.toml
@@ -18,7 +18,7 @@ mimalloc-rust = { version = "0.2" }
 [target.'cfg(not(target_os = "linux"))'.dependencies]
 mimalloc-rust = { version = "0.2" }
 
-[target.'cfg(all(target_os = "linux", not(all(target_env = "musl", target_arch = "aarch64"))))'.dependencies]
+[target.'cfg(all(any(target_os = "linux", target_os = "freebsd"), not(all(target_env = "musl", target_arch = "aarch64"))))'.dependencies]
 mimalloc-rust = { version = "0.2", features = ["local-dynamic-tls"] }
 
 [build-dependencies]
