--- pyproject.toml.orig	2025-12-05 02:58:45 UTC
+++ pyproject.toml
@@ -45,7 +45,7 @@ requires = [
 
 [build-system]
 requires = [
-    "hatchling==1.27.0",
+    "hatchling>=1.27.0",
 ]
 build-backend = "hatchling.build"
 
