--- pyproject.toml.orig	2025-10-26 23:13:25 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@
 [build-system]
 requires = [
-    "Cython == 3.1.3",
+    "Cython >= 3.1.3",
     "setuptools >= 40.6.0",  # Start of PEP 517 support for setuptools
 ]
 build-backend = "setuptools.build_meta"
