--- crates/zed/Cargo.toml.orig	2026-01-14 15:30:09 UTC
+++ crates/zed/Cargo.toml
@@ -84,7 +84,6 @@ copilot.workspace = true
 component.workspace = true
 component_preview.workspace = true
 copilot.workspace = true
-crashes.workspace = true
 dap_adapters.workspace = true
 db.workspace = true
 debug_adapter_extension.workspace = true
@@ -225,6 +224,9 @@ ashpd.workspace = true
 
 [target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
+
+[target.'cfg(not(target_os = "freebsd"))'.dependencies]
+crashes.workspace = true
 
 [dev-dependencies]
 call = { workspace = true, features = ["test-support"] }
