--- crates/zed/Cargo.toml.orig	2025-11-27 19:12:04 UTC
+++ crates/zed/Cargo.toml
@@ -42,7 +42,6 @@ copilot.workspace = true
 command_palette.workspace = true
 component.workspace = true
 copilot.workspace = true
-crashes.workspace = true
 dap_adapters.workspace = true
 db.workspace = true
 debug_adapter_extension.workspace = true
@@ -176,6 +175,9 @@ ashpd.workspace = true
 
 [target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
+
+[target.'cfg(not(target_os = "freebsd"))'.dependencies]
+crashes.workspace = true
 
 [dev-dependencies]
 call = { workspace = true, features = ["test-support"] }
