--- crates/zed/Cargo.toml.orig	2026-01-29 22:37:26 UTC
+++ crates/zed/Cargo.toml
@@ -90,7 +90,6 @@ copilot_ui.workspace = true
 copilot.workspace = true
 copilot_chat.workspace = true
 copilot_ui.workspace = true
-crashes.workspace = true
 dap_adapters.workspace = true
 db.workspace = true
 debug_adapter_extension.workspace = true
@@ -234,6 +233,9 @@ ashpd.workspace = true
 
 [target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 ashpd.workspace = true
+
+[target.'cfg(not(target_os = "freebsd"))'.dependencies]
+crashes.workspace = true
 
 [dev-dependencies]
 call = { workspace = true, features = ["test-support"] }
