# Sample configuration file for Redpanda Connect. It saves all messages to a file (/tmp/benthos.txt).
http:
  enabled: true
  address: 127.0.0.1:4195
  root_path: /
  debug_endpoints: false
input:
  http_server:
    path: /post
    ws_path: /post/ws
    ws_welcome_message: "Welcome to the Benthos Websocket API."
    allowed_verbs:
      - POST
    timeout: 5s
    cors:
      enabled: false
      allowed_origins: []
    sync_response:
      status: "200"
      headers:
        Content-Type: application/octet-stream
output:
  file:
    path: /tmp/benthos.txt
    codec: lines
shutdown_delay: 0s
shutdown_timeout: 20s
