--- pyproject.toml.orig	2026-01-13 07:47:21 UTC
+++ pyproject.toml
@@ -3,7 +3,7 @@ requires-python = ">=3.10"
 description = "A linter for YAML files."
 readme = {file = "README.rst", content-type = "text/x-rst"}
 requires-python = ">=3.10"
-license = "GPL-3.0-or-later"
+license = { text = "GPL-3.0-or-later" }
 authors = [{name = "Adrien VergÃ©"}]
 keywords = ["yaml", "lint", "linter", "syntax", "checker"]
 classifiers = [
@@ -42,7 +42,7 @@ build-backend = "setuptools.build_meta"
 
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools >= 77.0.3"]
+requires = ["setuptools >= 61"]
 
 [tool.setuptools]
 packages = ["yamllint", "yamllint.conf", "yamllint.rules"]
