--- pyproject.toml.orig	2024-09-12 19:54:11 UTC
+++ pyproject.toml
@@ -5,9 +5,9 @@ requires = [
     "murmurhash>=1.0.2,<1.1.0",
     "cymem>=2.0.2,<2.1.0",
     "preshed>=3.0.2,<3.1.0",
-    "blis>=1.0.0,<1.1.0",
-    "numpy>=2.0.0,<3.0.0; python_version < '3.9'",
-    "numpy>=2.0.0,<3.0.0; python_version >= '3.9'",
+    "blis>=1.0.0,<1.4.0",
+    "numpy>=0,<3.0.0; python_version < '3.9'",
+    "numpy>=0,<3.0.0; python_version >= '3.9'",
 ]
 build-backend = "setuptools.build_meta"
 
