-- remove jemalloc dependencies from Cargo.lock

--- Cargo.toml.orig	2025-12-09 21:46:20 UTC
+++ Cargo.toml
@@ -156,11 +156,6 @@ collapsible_if = "allow"
 [workspace.lints.clippy]
 collapsible_if = "allow"
 
-[patch.crates-io]
-# packed_simd_2 = { git = "https://github.com/rust-lang/packed_simd", rev = "e57c7ba11386147e6d2cbad7c88f376aab4bdc86" }
-# simd-json = { git = "https://github.com/ritchie46/simd-json", branch = "alignment" }
-tikv-jemallocator = { git = "https://github.com/pola-rs/jemallocator", rev = "c7991e5bb6b3e9f79db6b0f48dcda67c5c3d2936" }
-
 [profile.mindebug-dev]
 inherits = "dev"
 debug = "line-tables-only"
