--- pyproject.toml.orig	2025-07-08 03:14:55 UTC
+++ pyproject.toml
@@ -1,12 +1,11 @@ build-backend = "setuptools.build_meta"
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools>=77.0.3"]
+requires = ["setuptools>=61"]
 
 [project]
 name = "types-jsonschema"
 version = "4.24.0.20250708"
-license = "Apache-2.0"
-license-files = ["LICENSE"]
+license = { text = "Apache-2.0" }
 description = "Typing stubs for jsonschema"
 readme = { text = """\
 ## Typing stubs for jsonschema
@@ -51,5 +50,4 @@ dependencies = ['referencing']
 "Chat" = "https://gitter.im/python/typing"
 
 [tool.setuptools]
-packages = ['jsonschema-stubs']
 include-package-data = false
