--- pyproject.toml.orig	2025-11-27 20:56:57 UTC
+++ pyproject.toml
@@ -5,7 +5,7 @@ version = "1.9.2"
 [project]
 name = "Logbook"
 version = "1.9.2"
-license = "BSD-3-Clause"
+license = {text = "BSD-3-Clause"}
 authors = [
     { name = "Armin Ronacher", email = "armin.ronacher@active-4.com" },
     { name = "Georg Brandl" },
