--- pyproject.toml.orig	2026-02-11 07:27:21 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["uv_build>=0.9.0,<0.10.0"]
+requires = ["uv_build>0"]
 build-backend = "uv_build"
 
 [project]
