--- pyproject.toml.orig	2026-01-15 07:27:14 UTC
+++ pyproject.toml
@@ -6,8 +6,7 @@ authors = [
 authors = [
   {name = "khal contributors", email = "khal@lostpackets.de"},
 ]
-license = "MIT"
-license-files = ["doc/source/license.rst"]
+license = {text="MIT"}
 classifiers = [
   "Development Status :: 4 - Beta",
   "Environment :: Console :: Curses",
@@ -66,7 +65,7 @@ ikhal = "khal.cli:main_ikhal"
 ikhal = "khal.cli:main_ikhal"
 
 [build-system]
-requires = ["setuptools>=77", "setuptools_scm>=8"]
+requires = ["setuptools>=63", "setuptools_scm>=8"]
 build-backend = "setuptools.build_meta"
 
 [tool.setuptools.packages.find]
