--- pyproject.toml.orig	2024-04-01 17:37:16 UTC
+++ pyproject.toml
@@ -2,10 +2,8 @@ requires = [
 requires = [
     "setuptools",
     "scikit-build",
-    "cython>=3",
-    "cmake",
-    "ninja",
-    "numpy>=2.0.0",
+    "cython",
+    "numpy",
 ]
 build-backend = "setuptools.build_meta"
 
