--- pyproject.toml.orig	2025-07-03 15:37:36 UTC
+++ pyproject.toml
@@ -3,16 +3,12 @@ requires = ["setuptools"]
 requires = ["setuptools"]
 
 [project]
-name = "SCons"
+name = "scons"
 description = "Open Source next-generation build tool."
 requires-python = ">=3.7"
-license = "MIT"  # PEP 639 form (new - setuptools >= 77.0)
+license = { text = "MIT" }  # PEP 639 form (new - setuptools >= 77.0)
 # Should include docbook license, but this fails:
 # license = "MIT AND DocBook-stylesheet"
-license-files = [
-    "LICENSE",
-    "SCons/Tool/docbook/docbook-xsl-1.76.1/COPYING",
-]
 readme = { file = "README-package.rst", content-type = "text/x-rst" }
 authors = [{ name = "William Deegan", email = "bill@baddogconsulting.com" }]
 dynamic = ["version"]
