[build]

# Use bundled crates; this should permit offline build.
vendor = true

# In addition to rustc, rust-std and rust-docs, build Cargo.
extended = true

# python(1) location.
python = "%PYTHON_CMD%"

# Do we want to build docs?
docs = %DOCS%

[install]

# Install location.
prefix = "%PREFIX%"
sysconfdir = "%SYSCONFDIR%"
mandir = "%MANDIR%"

[rust]

# Rust release channel.
channel = "%CHANNEL%"

[target.%TARGET%]

[dist]

# Do not build the source archive.
src-tarball = false
