--- pyproject.toml.orig	2026-01-09 18:11:11 UTC
+++ pyproject.toml
@@ -34,7 +34,7 @@ dependencies = [
     "platformdirs>=3.11.0",
     "requests>=2.32.0",
     "scikit-learn>=1.4.0",
-    "scipy>=1.12.0",
+    "scipy>=1.11.0",
     "shapely>=2.0",
 ]
 
