--- pyproject.toml.orig	2025-12-22 18:24:26 UTC
+++ pyproject.toml
@@ -1,3 +1,3 @@
 [build-system]
-requires = ["setuptools >= 78.1.1"]
+requires = ["setuptools >= 61"]
 build-backend = "setuptools.build_meta"
