--- pyproject.toml.orig	2024-11-16 07:59:21 UTC
+++ pyproject.toml
@@ -42,12 +42,12 @@ colorama = "^0.4.1"
 questionary = "^2.0"
 decli = "^0.6.0"
 colorama = "^0.4.1"
-termcolor = ">= 1.1, < 3"
+termcolor = ">= 1.1"
 packaging = ">=19"
 tomlkit = ">=0.5.3,<1.0.0"
 jinja2 = ">=2.10.3"
 pyyaml = ">=3.08"
-argcomplete = ">=1.12.1,<3.6"
+argcomplete = ">=1.12.1"
 typing-extensions = { version = "^4.0.1", python = "<3.8" }
 charset-normalizer = ">=2.1.0,<4"
 # Use the Python 3.11 and 3.12 compatible API: https://github.com/python/importlib_metadata#compatibility
