--- pyproject.toml.orig	2026-02-03 18:17:35 UTC
+++ pyproject.toml
@@ -23,7 +23,7 @@ name = "grpcio"
 
 [project]
 name = "grpcio"
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 description = "HTTP/2-based RPC framework"
 readme = {file = "src/python/grpcio/README.rst", content-type = "text/x-rst"}
 authors = [{name = "The gRPC Authors", email = "grpc-io@googlegroups.com"}]
