--- pyproject.toml.orig	2006-07-24 01:21:28 UTC
+++ pyproject.toml
@@ -32,7 +32,7 @@ dependencies = [
   "version",
 ]
 dependencies = [
-  "toml-fmt-common==1.1",
+  "toml-fmt-common>=1.1",
 ]
 urls."Bug Tracker" = "https://github.com/tox-dev/toml-fmt/issues"
 urls."Changelog" = "https://github.com/tox-dev/toml-fmt/blob/main/tox-toml-fmt/CHANGELOG.md"
