--- pyproject.toml.orig	2025-11-05 03:04:39 UTC
+++ pyproject.toml
@@ -1,12 +1,11 @@ build-backend = "setuptools.build_meta"
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools>=77.0.3"]
+requires = ["setuptools>=61"]
 
 [project]
 name = "types-protobuf"
 version = "6.32.1.20251105"
-license = "Apache-2.0"
-license-files = ["LICENSE"]
+license = { text = "Apache-2.0" }
 description = "Typing stubs for protobuf"
 readme = { text = """\
 ## Typing stubs for protobuf
@@ -52,5 +51,4 @@ dependencies = []
 "Chat" = "https://gitter.im/python/typing"
 
 [tool.setuptools]
-packages = ['google-stubs']
 include-package-data = false
