Normalize the bdist wheel name to avoid staging errors.

--- pyproject.toml.orig	2025-09-30 16:12:51 UTC
+++ pyproject.toml
@@ -3,7 +3,7 @@ build-backend = "setuptools.build_meta"
 build-backend = "setuptools.build_meta"
 
 [project]
-name = "rlPyCairo"
+name = "rlpycairo"
 description="Plugin backend renderer for reportlab.graphics.renderPM"
 readme = "README.txt"
 authors=[
