--- Cargo.toml.orig	2025-12-19 20:11:31 UTC
+++ Cargo.toml
@@ -27,8 +27,7 @@ typst-kit = { version = "0.14.1", features = [
 typst = "0.14.1"
 typst-kit = { version = "0.14.1", features = [
   "downloads",
-  "embed-fonts",
-  "vendor-openssl",
+  "embed-fonts"
 ] }
 typst-pdf = "0.14.1"
 typst-svg = "0.14.1"
