Use system OpenSSL instead of vendored one

https://github.com/panter-dsd/tatuin/commit/2380e344736bd5622a48ba31f58a28af1c0a547f#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R43
--- Cargo.toml.orig	2026-01-16 04:09:38 UTC
+++ Cargo.toml
@@ -39,7 +39,7 @@ uuid = { version = "1.19.0", features = ["v4"] }
 tracing-appender = "0.2.4"
 tracing-subscriber = "0.3.19"
 uuid = { version = "1.19.0", features = ["v4"] }
-openssl = { version = "0.10", features = ["vendored"] }
+openssl = { version = "0.10", features = [] }
 tatuin-core = { path = "./tatuin-core", version = "0.4.0" }
 tatuin-providers = { path = "./tatuin-providers", version = "0.5.0" }
 dirs = "6.0.0"
