--- pyproject.toml.orig        2025-12-05 08:33:13 UTC
+++ pyproject.toml
@@ -3,7 +3,7 @@ build-backend = "setuptools.build_meta"
 build-backend = "setuptools.build_meta"

 [project]
-name = "Cerberus"
+name = "cerberus"
 version = "1.3.8"
 description = """\
 Lightweight, extensible schema and data validation tool for Python\
