--- pyproject.toml.orig	2026-01-05 06:06:35 UTC
+++ pyproject.toml
@@ -6,7 +6,6 @@ readme = "README.md"
 version = "1.56.0"
 description = "GenAI Python SDK"
 readme = "README.md"
-license = "Apache-2.0"
 requires-python = ">=3.10"
 authors = [
     { name = "Google LLC", email = "googleapis-packages@google.com" },
