--- pyproject.toml.orig	2025-12-23 00:54:52 UTC
+++ pyproject.toml
@@ -6,8 +6,7 @@ readme = "README.rst"
 name = "pyparsing"
 authors = [{name = "Paul McGuire", email = "ptmcg.gm+pyparsing@gmail.com"}]
 readme = "README.rst"
-license = "MIT"
-license-files = ["LICENSE"]
+license = { text = "MIT License" }
 dynamic = ["version", "description"]
 requires-python = ">=3.9"
 classifiers = [
