--- pyproject.toml.orig	2025-11-18 10:57:23 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=77", "setuptools_scm[toml]>=3.4"]
+requires = ["setuptools>=42", "setuptools_scm[toml]>=3.4"]
 build-backend = "setuptools.build_meta"
 
 [tool.setuptools_scm]
@@ -26,7 +26,7 @@ keywords = ["tab", "complete", "completion", "shell", 
 readme = "README.rst"
 requires-python = ">=3.9"
 keywords = ["tab", "complete", "completion", "shell", "bash", "zsh", "argparse"]
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Environment :: Console",
