--- pyproject.toml.orig	2025-12-01 20:27:56 UTC
+++ pyproject.toml
@@ -7,7 +7,7 @@ readme = "README.rst"
 version = "2.0.0"
 description = "Sphinx SVG to PDF or PNG converter extension"
 readme = "README.rst"
-license = "BSD-2-Clause"
+license = {text = "BSD-2-Clause"}
 authors = [
   {name = "Stefan Wiehler", email = "sphinx_contribute@missinglinkelectronics.com"},
 ]
