--- pyproject.toml.orig	2025-11-25 18:46:01 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ requires = [
 [build-system]
 requires = [
-    "Cython == 3.2.1",
+    "Cython >= 3.2.1",
     "setuptools >= 42.0.0",  # Supports license_files
 ]
 build-backend = "setuptools.build_meta"
