--- Cargo.toml.orig	2025-11-25 15:29:10 UTC
+++ Cargo.toml
@@ -45,7 +45,7 @@ chrono = { version = "0.4.42", features = ["serde"] }
 tracing = { version = "0.1.40", features = ["attributes"] }
 tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
 chrono = { version = "0.4.42", features = ["serde"] }
-git2 = { version = "0.20.2", features = ["vendored-libgit2", "vendored-openssl"] }
+git2 = { version = "0.20.2", features = ["vendored-libgit2"] }
 tempfile = "3.23.0"
 dirs = "6.0.0"
 semver = "1.0.23"
