Relax version requirements for py-uv-build.

--- pyproject.toml.orig	2026-02-06 12:46:32 UTC
+++ pyproject.toml
@@ -35,7 +35,7 @@ classifiers = [
 
 
 [build-system]
-requires = ["uv_build>=0.9.17,<0.10.0"]
+requires = ["uv_build>=0.9.17,<0.11.0"]
 build-backend = "uv_build"
 
 [tool.uv.build-backend]
