--- pyproject.toml.orig	2025-11-21 17:57:14 UTC
+++ pyproject.toml
@@ -9,7 +9,7 @@ requires-python = ">=3.10"
 description = "Simple SQL in Python"
 readme = "README.rst"
 requires-python = ">=3.10"
-license = "BSD-2-Clause"
+license = {file="LICENSE"}
 classifiers = [
     "Programming Language :: Python :: 3",
     "Programming Language :: SQL",
