--- pyproject.toml.orig	2025-10-26 15:11:44 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 77.0"]
+requires = ["setuptools >= 61.0"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -8,7 +8,7 @@ authors = [
 authors = [
     {name = "Saurabh Kumar", email = "me+github@saurabh-kumar.com"},
 ]
-license = "BSD-3-Clause"
+license = {text = "BSD-3-Clause"}
 keywords = [
     "environment variables",
     "deployments",
