--- pyproject.toml.orig	2023-09-14 13:29:30 UTC
+++ pyproject.toml
@@ -20,10 +20,6 @@ documentation = "https://cyclonedx-python-library.read
 packages = [
   { include = "cyclonedx" }
 ]
-include = [
-  "README.md", "LICENSE", "NOTICE",
-  { path = "tests", format = "sdist" },
-]
 classifiers = [
   # Trove classifiers - https://packaging.python.org/specifications/core-metadata/#metadata-classifier
   # Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
@@ -53,8 +49,8 @@ keywords = [
 [tool.poetry.dependencies]
 # ATTENTION: keep `deps.lowest.r` file in sync
 python = "^3.7"
-packageurl-python = ">= 0.11"
-py-serializable = "^0.11.1"
+packageurl-python = ">= 0.9"
+py-serializable = ">= 0.11.1"
 sortedcontainers = "^2.4.0"
 license-expression = "^30"
 
