--- pyproject.toml.orig	2025-11-20 20:00:00 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=64"]
+requires = ["setuptools"]
 build-backend = "setuptools.build_meta"
 
 [project]
