--- pyproject.toml.orig	2025-11-06 06:48:39 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 77.0"]
+requires = ["setuptools >= 63.0"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -7,8 +7,8 @@ readme = "README.rst"
 version = "5.0.4"
 description = "XPath 1.0/2.0/3.0/3.1 parsers and selectors for ElementTree and lxml"
 readme = "README.rst"
-license = "MIT"
-license-files = ["LICENSE"]
+license = {text="MIT"}
+#license-files = ["LICENSE"]
 requires-python = ">=3.9"
 authors = [
     { name = "Davide Brunato", email = "brunato@sissa.it" },
