--- pyproject.toml.orig	2026-01-05 14:22:45 UTC
+++ pyproject.toml
@@ -1,8 +1,8 @@ requires = [
 [build-system]
 requires = [
-    "setuptools>=77.0.3",
-    "cython>=3.1,<=3.2",
-    "numpy>=2,<3",
+    "setuptools>=61",
+    "cython>=3.1",
+    "numpy<3",
 ]
 build-backend = "setuptools.build_meta"
 
@@ -18,8 +18,7 @@ keywords = ["gis", "raster", "gdal"]
 description = "Fast and direct raster I/O for use with NumPy"
 readme = "README.rst"
 keywords = ["gis", "raster", "gdal"]
-license = "BSD-3-Clause"
-license-files = ["LICENSE.txt", "AUTHORS.txt"]
+license = {text = "BSD-3-Clause"}
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Intended Audience :: Developers",
@@ -34,7 +33,7 @@ classifiers = [
     "Topic :: Multimedia :: Graphics :: Graphics Conversion",
     "Topic :: Scientific/Engineering :: GIS",
 ]
-requires-python = ">=3.12"
+requires-python = ">=3.11"
 dependencies = [
     "affine",
     "attrs",
@@ -42,7 +41,7 @@ dependencies = [
     # Avoid https://github.com/pallets/click/issues/2939
     "click>=4.0,!=8.2.*",
     "cligj>=0.5",
-    "numpy>=2",
+    "numpy",
     "pyparsing",
 ]
 
