--- pyproject.toml.orig	2025-11-29 13:01:05.743721000 -0800
+++ pyproject.toml	2025-11-29 13:01:10.079226000 -0800
@@ -1,30 +1,11 @@
 [build-system]
 requires = [
-    "setuptools>=61.0",
+    "setuptools",
     "wheel",
     "scikit-build",
-    "cmake",
-    "ninja",
-    "swig",
     "numpy",
 ]
 build-backend = "setuptools.build_meta"
 
-[project]
-name = "ezc3d"
-dynamic = ["version"]
-dependencies = [
-    "numpy",
-]
-description = "Easy to use C3D reader/writer for C++, Python, and Matlab"
-readme = "README.md"  # This links to your README file
-authors = [
-    {name = "Michaud, Benjamin"},
-    {name = "Begon, MickaÃ«l"}
-]
-license-files = ["LICENSE"]
-urls = { "Homepage" = "https://github.com/pyomeca/ezc3d" }
-requires-python = ">=3.10"
-
 [tool.cibuildwheel]
 build-frontend = "build"
