--- pyproject.toml.orig	2025-11-06 16:08:46 UTC
+++ pyproject.toml
@@ -2,7 +2,7 @@ readme = 'README.rst'
 name = "asdf"
 description = "Python implementation of the ASDF Standard"
 readme = 'README.rst'
-license-files = ['LICENSE']
+license = { file = 'LICENSE' }
 authors = [{ name = 'The ASDF Developers' }]
 requires-python = '>=3.9'
 classifiers = [
