--- pyproject.toml.orig	2025-11-17 16:52:01 UTC
+++ pyproject.toml
@@ -6,7 +6,7 @@ requires = [
     "cymem>=2.0.2,<2.1.0",
     "preshed>=3.0.2,<3.1.0",
     "blis>=1.3.0,<1.4.0",
-    "numpy>=2.0.0,<3.0.0",
+    "numpy>=1.19.0,<3.0.0",
 ]
 build-backend = "setuptools.build_meta"
 
