--- pyproject.toml.orig	2026-01-30 19:14:27 UTC
+++ pyproject.toml
@@ -9,7 +9,7 @@ readme = "README.md"
   {name = "Leonardo Uieda", email = "leo@uieda.com"}
 ]
 readme = "README.md"
-license = "BSD-3-Clause"
+license = {text = "BSD-3-Clause"}
 keywords = ["data", "download", "caching", "http"]
 classifiers = [
     "Development Status :: 5 - Production/Stable",
