--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -25,7 +25,7 @@ dependencies = [
 dependencies = [
     "GitPython~=3.1",
     "colorama~=0.4",
-    "packaging~=25.0",
+    "packaging>=25.0",
     "termcolor~=3.2",
 ]
 
