--- pyproject.toml.orig	2025-09-27 13:07:52 UTC
+++ pyproject.toml
@@ -30,7 +30,7 @@ keywords = [
     "podman",
     "podman-compose",
 ]
-license = "GPL-2.0-only"
+license = { text = "GPL-2.0-only" }
 dynamic = ["version", "readme"]

 [project.urls]
