--- pyproject.toml.orig	2025-11-29 13:53:51 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 77.0.3"]
+requires = ["setuptools >= 61"]
 build-backend = "setuptools.build_meta"
 
 [project]
