--- pyproject.toml.orig	2025-02-14 11:36:11 UTC
+++ pyproject.toml
@@ -45,7 +45,7 @@ types-pyyaml = "^6.0.12.20240311"
 python-dateutil = "^2.9.0.post0"
 pyyaml = "^6.0.1"
 types-pyyaml = "^6.0.12.20240311"
-types-python-dateutil = "^2.9.0.20240316"
+types-python-dateutil = "^2.8.19"
 
 [tool.poetry.group.dev.dependencies]
 behave = "^1.2.6"
