--- cargo-crates/libsqlite3-sys-0.35.0/Cargo.toml.orig	2026-01-30 17:01:12 UTC
+++ cargo-crates/libsqlite3-sys-0.35.0/Cargo.toml
@@ -43,10 +43,6 @@ bundled-sqlcipher = ["bundled"]
     "bundled_bindings",
 ]
 bundled-sqlcipher = ["bundled"]
-bundled-sqlcipher-vendored-openssl = [
-    "bundled-sqlcipher",
-    "openssl-sys/vendored",
-]
 bundled-windows = [
     "cc",
     "bundled_bindings",
