--- cargo-crates/reqwest-0.12.26/Cargo.toml.orig	2026-01-30 17:17:12 UTC
+++ cargo-crates/reqwest-0.12.26/Cargo.toml
@@ -141,10 +141,6 @@ native-tls-alpn = [
     "native-tls-crate?/alpn",
     "hyper-tls?/alpn",
 ]
-native-tls-vendored = [
-    "native-tls",
-    "native-tls-crate?/vendored",
-]
 rustls-tls = ["rustls-tls-webpki-roots"]
 rustls-tls-manual-roots = [
     "rustls-tls-manual-roots-no-provider",
