--- pyproject.toml.orig	2025-12-25 19:30:14 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [project]
-name = "Flask-SocketIO"
+name = "flask-socketio"
 version = "5.6.0"
 authors = [
     { name = "Miguel Grinberg", email = "miguel.grinberg@gmail.com" },
