--- Cargo.toml.orig	2025-11-27 19:56:36 UTC
+++ Cargo.toml
@@ -24,7 +24,7 @@ exclude = [
 ]

 [dependencies]
-git2 = { version = "0.20", features = ["vendored-openssl", "vendored-libgit2"] }
+git2 = { version = "0.20", features = ["vendored-libgit2"] }
 ratatui = "0.29"
 crossterm = "0.29"
 tree-sitter = "0.25"
