--- pyproject.toml.orig	2020-02-02 00:00:00 UTC
+++ pyproject.toml
@@ -34,9 +34,9 @@ classifiers = [
 ]
 dependencies = [
   "httpx>=0.23,<1",
-  "anyio~=3.0",
+  "anyio>=3.0",
   "msgpack~=1.0",
-  "fasteners>=0.16.3,<0.18.0",
+  "fasteners>=0.16.3",
   "attrs>=21.4,<24.0",
   "aiorwlock~=1.2"
 ]
