--- pyproject.toml.orig	2022-11-09 12:37:21 UTC
+++ pyproject.toml
@@ -2,7 +2,7 @@ requires = [
 requires = [
     "scikit-build-core",
     "pybind11<3",
-    "numpy>=2.0.1"
+    "numpy>=1.25"
 ]
 build-backend = "scikit_build_core.build"
 
