--- cargo-crates/ring-0.17.8/Cargo.toml.orig	1970-01-01 00:00:01 UTC
+++ cargo-crates/ring-0.17.8/Cargo.toml
@@ -220,7 +220,7 @@ wasm32_unknown_unknown_js = ["getrandom/js"]
 unstable-testing-arm-no-neon = []
 wasm32_unknown_unknown_js = ["getrandom/js"]
 
-[target."cfg(all(any(target_os = \"android\", target_os = \"linux\"), any(target_arch = \"aarch64\", target_arch = \"arm\")))".dependencies.libc]
+[target."cfg(all(any(target_os = \"android\", target_os = \"freebsd\", target_os = \"linux\"), any(target_arch = \"aarch64\", target_arch = \"arm\")))".dependencies.libc]
 version = "0.2.148"
 default-features = false
 
