--- pyproject.toml.orig	2025-11-26 15:41:24 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=64", "wheel"]
+requires = ["setuptools", "wheel"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -73,4 +73,4 @@ line-length = 100
 line-length = 100
 
 [tool.setuptools]
-include-package-data = true
\ No newline at end of file
+include-package-data = true
