--- pyproject.toml.orig	2024-07-16 11:51:30 UTC
+++ pyproject.toml
@@ -215,16 +215,6 @@ pydantic = ">=1.7.4, <3"
 # See https://github.com/matrix-org/synapse/issues/15858
 pydantic = ">=1.7.4, <3"
 
-# This is for building the rust components during "poetry install", which
-# currently ignores the `build-system.requires` directive (c.f.
-# https://github.com/python-poetry/poetry/issues/6154). Both `pip install` and
-# `poetry build` do the right thing without this explicit dependency.
-#
-# This isn't really a dev-dependency, as `poetry install --no-dev` will fail,
-# but the alternative is to add it to the main list of deps where it isn't
-# needed.
-setuptools_rust = ">=1.3"
-
 # This is used for parsing multipart responses
 python-multipart = ">=0.0.9"
 
@@ -372,7 +362,7 @@ tomli = ">=1.2.3"
 # runtime errors caused by build system changes.
 # We are happy to raise these upper bounds upon request,
 # provided we check that it's safe to do so (i.e. that CI passes).
-requires = ["poetry-core>=1.1.0,<=1.9.0", "setuptools_rust>=1.3,<=1.8.1"]
+requires = ["poetry-core>=1.1.0,<=1.9.0", "setuptools_rust>=1.3,<=1.10.1"]
 build-backend = "poetry.core.masonry.api"
 
 
