--- pyproject.toml.orig	2025-07-15 03:23:16 UTC
+++ pyproject.toml
@@ -1,12 +1,11 @@ build-backend = "setuptools.build_meta"
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools>=77.0.3"]
+requires = ["setuptools>=61"]
 
 [project]
 name = "types-docutils"
 version = "0.21.0.20250715"
-license = "Apache-2.0"
-license-files = ["LICENSE"]
+license = { text = "Apache-2.0" }
 description = "Typing stubs for docutils"
 readme = { text = """\
 ## Typing stubs for docutils
@@ -55,5 +54,4 @@ dependencies = []
 "Chat" = "https://gitter.im/python/typing"
 
 [tool.setuptools]
-packages = ['docutils-stubs']
 include-package-data = false
