--- pyproject.toml.orig	1970-01-01 00:00:00 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@
 [build-system]
-build-backend = "uv_build"
-requires = ["uv_build>=0.9.0,<0.10.0"]
+build-backend = "poetry.core.masonry.api"
+requires = ["poetry-core>=1.0.0"]
 
 [project]
 name = "cucumber-expressions"
