--- pyproject.toml.orig	2026-01-23 15:28:32 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@ requires = [
 [build-system]
 build-backend = "setuptools.build_meta"
 requires = [
-     "setuptools >= 77.0.3"
+     "setuptools >= 61"
 ]
 
 [project]
@@ -14,11 +14,7 @@ maintainers = [
 maintainers = [
     { name = "Jason Madden", email = "jason@seecoresoftware.com" }
 ]
-license = "MIT AND Python-2.0"
-license-files = [
-    'LICENSE',
-    'LICENSE.PSF',
-]
+license = { text = "MIT AND Python-2.0" }
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Intended Audience :: Developers",
